version: '3'
services:
  mongo:
    image: library/mongo:4.4.8
    environment:
      MONGO_INITDB_DATABASE: ntf-db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"

  test-mongodb:
    image: library/mongo:4.4.8
    environment:
      MONGO_INITDB_DATABASE: ntf-db-test
    ports:
      - "27018:27017"
