version: '3'
services:
  mongo:
    image: library/mongo:6.0.5
    environment:
      MONGO_INITDB_DATABASE: ntf-db
    ports:
      - "27017:27017"

  test-mongodb:
    image: library/mongo:6.0.5
    environment:
      MONGO_INITDB_DATABASE: ntf-db-test
    ports:
      - "27018:27017"
