[build]
builder = "RAILPACK"

[deploy]
multiRegionConfig = { "europe-west4-drams3a" = { numReplicas = 1 } }
limitOverride = { containers = { cpu = 4, memoryBytes = 4000000000 } }
runtime = "V2"
numReplicas = 1
healthcheckPath = "/health"
sleepApplication = false
useLegacyStacker = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
