version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ntf-db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081

  test-mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ntf-db-test
    ports:
      - "27018:27017"
