version: '3'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongodb'
      MONGO_INITDB_ROOT_PASSWORD: 'mongodb'
      MONGO_INITDB_DATABASE: 'ntf-db'
    ports:
      - "27017:27017"
