[package]
name = "nine-to-five"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.12", features = ["with-axum"] }
askama_axum = "0.4.0"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "any", "postgres"] }
chrono = { version = "0.4.34", features = ["clock"] }
oauth2 = "4.4.2"
axum-extra = { version = "0.9.2", features = ["cookie-private"] }
serde = "1.0.196"
