spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ntf-db
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  jackson:
    default-property-inclusion: non_null

auth0:
  issuer: https://ninetofive.eu.auth0.com/
  audience: https://api.ntf.io

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN

